// These token are generated by twitter when you create an app
module.exports = {
	consumer_key: "LDqumGfIyJKIe9WIayrsCqiLN",
	consumer_secret: "dHCjrndq14a3mTXdRoKD87Tst30rPUwCkJENd4Hv25t1Fd8nQo",
	access_token: "949621081169715205-DN9oCHi2WRfEXL1zDrWjgpzMM2KvQH4",
	access_token_secret: "fnp0Lygj2GsfBjNA8t32FjMCi6Wxpjli7veI9Dmc3b6wN"
};
